### ISSUE TITLE
Questions about the metrics in the paper

### ISSUE THREAD

**Issue by RobertLuo1** [showlab/UniVTG#23]
Thanks for your amazing work. When I read the metrics about the charades-sta, I find that the R0.5 and R0.7 of Moment Detr is not consistent with its paper reported.
![image](https://github.com/showlab/UniVTG/assets/72377255/565b1499-f28a-472d-ad2c-847c9ccbcd3b)
![image](https://github.com/showlab/UniVTG/assets/72377255/30fa2c2b-be36-4a48-8ad3-483a5b6026f5)

And one more question is that which set are you evaluated in TaCOS dataset (val or test).

**Comment by EasonXiao-888** [comment]
The same confusion above mentioned

**Comment by QinghongLin** [comment]
Hi @RobertLuo1 @EasonXiao-888 
Thanks for asking!
The inconsistent result here is because the offical Moment_DETR do not report the R@0.3 and mIoU, 
and I rerun their codebase on this dataset based on their recommended parameter settings (w/o HT100M PT).
I saved the best one based on the **mIoU metrics** (which is more comprehensive than R@0.5), thus the R1@0.5 may slightly lower even with best mIoU metrics.

**Comment by RobertLuo1** [comment]
I got it and thanks for your reply!!
